### PR TITLE
feat(cli): Update the import cli to output preview links for individual configs. BM-869

### PR DESCRIPTION
**Pull request by Wentao-Kuang**
### Why?
As we separated expired/disabled configs as individual config files in [basemaps-config](https://github.com/linz/basemaps-config) repo. Now we need the ci process to automatically pick the config changes and inserts for individual imagery.

### Description of Changes:
- Update the basemaps cli import command to output changes for all tileset configs that only have a single layer.
- relocate and reuse the prepare preview links logic into separated functions
- Tested locally and test output markdown will update into PR comments soon.

#### Author Checklist:
- [ ] Tests updated
- [ ] Docs updated
- [ ] Issue linked in PR title

[BM-869]: https://toitutewhenua.atlassian.net/browse/BM-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Wentao-Kuang** [comment]
Output of locally test with aerial change and insert which means nothing broken, and a new individual layer inserted. 


# Aerial Config Inserts
### test_aerial_geographx_nz_texture_shade_2012_8-0m
 - [WebMercatorQuad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&i=geographx-nz-texture-shade-2012-8m&p=WebMercatorQuad&debug#@-40.979898,172.265625,z12) -- [Aerial](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=WebMercatorQuad&debug#@-40.979898,172.265625,z12)
# Individual Layer Inserts
### test_individual_tauranga-urban-2017-0.1m
 - [NZTM2000Quad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&i=tauranga-urban-2017-0.1m&p=NZTM2000Quad&debug#@-37.710551,176.227821,z9) -- [Aerial](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=NZTM2000Quad&debug#@-37.710551,176.227821,z9)
 - [WebMercatorQuad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&i=tauranga-urban-2017-0.1m&p=WebMercatorQuad&debug#@-37.722935,176.226196,z0) -- [Aerial](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=WebMercatorQuad&debug#@-37.722935,176.226196,z0)

**Comment by dwsilk** [comment]
Looking good, but Individual Layer Inserts shouldn't have Aerial links?

**Comment by Wentao-Kuang** [comment]
New test remove the aerial link for individual previews.

# Aerial Config Inserts
### test_aerial_geographx_nz_texture_shade_2012_8-0m
 - [WebMercatorQuad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&i=geographx-nz-texture-shade-2012-8m&p=WebMercatorQuad&debug#@-40.979898,172.265625,z12) -- [Aerial](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=WebMercatorQuad&debug#@-40.979898,172.265625,z12)
# Aerial Config Updates
### taupo_2023_0.075m
 - Zoom level updated. min zoom 14 -> 13 [NZTM2000Quad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=NZTM2000Quad&debug#@-38.709973,176.040295,z9) [WebMercatorQuad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=WebMercatorQuad&debug#@-38.709089,176.039429,z12)
# Individual Layer Inserts
### test_individual_tauranga-urban-2017-0.1m
 - [NZTM2000Quad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&i=tauranga-urban-2017-0.1m&p=NZTM2000Quad&debug#@-37.710551,176.227821,z9)
 - [WebMercatorQuad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&i=tauranga-urban-2017-0.1m&p=WebMercatorQuad&debug#@-37.722935,176.226196,z0)
# Individual Layer Updates
### tauranga-winter-2022-0.1m
 - Zoom level updated. max zoom 32 -> 14 [NZTM2000Quad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=NZTM2000Quad&debug#@-37.707514,176.238091,z9) [WebMercatorQuad](https://dev.basemaps.linz.govt.nz/?config=config/config.json&p=WebMercatorQuad&debug#@-37.707726,176.242676,z12)

**Comment by dwsilk** [comment]
Prefecto

**Review by blacha — APPROVED** [review]

**Pull request merged**
